version: "3"
services:
  domino_db:
    image: postgres
    env_file:
      - .env
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  domino_api:
    build:
      context: .
      dockerfile: .docker/api.Dockerfile
    env_file:
      - .env
    volumes:
      - ./api:/domino/api
    depends_on:
      - domino_db

  domino_client:
    build:
      context: .
      dockerfile: .docker/client.Dockerfile
    depends_on: 
      - domino_api
  domino_client:
    build:
      context: .
      dockerfile: .docker/client.Dockerfile
    volumes:
      - ./client/:/domino/client